# Общие интерфейсы EPC

[S1-MME]
  protocol = S1AP
  ip = 127.0.0.1
  port = 36412
  mcc = 250
  mnc = 20
  to = eNodeB

[Gb]
  protocol = BSSGP/NS
  ip = 127.0.0.1
  port = 2152
  mcc = 250
  mnc = 20
  to = BSC/PCU

[S6a]
  protocol = Diameter
  ip = 127.0.0.1
  port = 3868
  to = HSS

[S11]
  protocol = GTP-C
  ip = 127.0.0.1
  port = 2123
  to = SGW

[Gn/Gp]
  protocol = GTP-C/GTP-U
  ip = 127.0.0.1
  port = 2123/2152
  to = GGSN/SGW/PGW