# vMME configuration
mcc = 250
mme-code = 1
mme-group-id = 1
mme-name = mme01.vepc.local
mnc = 20
s11-bind-ip = 127.0.0.1
s11-bind-port = 2123
s1ap-bind-ip = 127.0.0.1
s1ap-bind-port = 36412
s6a-bind-ip = 127.0.0.1
s6a-bind-port = 3868
s6a-hss-host = hss.vepc.local
s6a-hss-realm = epc.mnc001.mcc001.3gppnetwork.org
