# vSGSN configuration
gb-bind-ip = 127.0.0.1
gb-bind-port = 2152
gb-nsip = 127.0.0.1
gb-nsvc = 1
gn-gtp-c-bind-ip = 127.0.0.1
gn-gtp-c-port = 2123
gn-gtp-u-bind-ip = 127.0.0.1
gn-gtp-u-port = 2152
iups-enabled = false
mcc = 250
mnc = 20
sgsn-code = 1
